[package]
edition = "2021"
name    = "example-todo-list"
publish = false
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.axum]
features = [""]
version  = "0.2"
